
Set Warnings "-native-compiler".
From Tableaux Require Import All.

Definition T : EForm :=
	ENeg (EAll "X137" (EAll "X239" (EAll "X341" (EAll "X443" (EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")]))))))))))))) 
.

Definition subst := translate_substitution [("X749_59", (EFun "skolem@A33@0" [])); ("X851_60", (EFun "skolem@B35@0" []))].


Definition T_Proof : ExtendedRuleTree.
Proof.
apply (mkUnaryNode ( AlphaNegNeg (Neg (Neg [[ EAll "X137" (EAll "X239" (EAll "X341" (EAll "X443" (EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")])))))))))))) ]])) ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X137" (EAll "X239" (EAll "X341" (EAll "X443" (EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")])))))))))))) ]] "X137_53" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X239" (EAll "X341" (EAll "X443" (EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")]))))))))))) ]] "X239_54" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X341" (EAll "X443" (EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")])))))))))) ]] "X341_55" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X443" (EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")]))))))))) ]] "X443_56" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X545" (EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")])))))))) ]] "X545_57" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X647" (EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545_57")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")]))))))) ]] "X647_58" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X749" (EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545_57")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647_58")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")])))))) ]] "X749_59" ) ).
apply (mkUnaryNode ( GammaAll [[ EAll "X851" (EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545_57")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647_58")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749_59")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851")])) (EEx "B35" (EPred "s" [(EVar "B35")]))))) ]] "X851_60" ) ).
apply (mkUnaryNode ( AlphaAnd [[ EAnd (EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545_57")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647_58")])) (EEx "T31" (EPred "s" [(EVar "T31")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X749_59")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851_60")])) (EEx "B35" (EPred "s" [(EVar "B35")])))) ]] ) ).
apply (mkUnaryNode ( AlphaAnd [[ EAnd (EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")]))))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X545_57")])) (EEx "S29" (EPred "r" [(EVar "S29")]))) (EAnd (ENeg (EPred "s" [(EVar "X647_58")])) (EEx "T31" (EPred "s" [(EVar "T31")])))) ]] ) ).
apply (mkUnaryNode ( AlphaAnd [[ EAnd (EOr (EAnd (ENeg (EPred "p" [(EVar "X137_53")])) (EEx "Y21" (EPred "p" [(EVar "Y21")]))) (EAnd (ENeg (EPred "q" [(EVar "X239_54")])) (EEx "Z23" (EPred "q" [(EVar "Z23")])))) (EOr (EAnd (ENeg (EPred "r" [(EVar "X341_55")])) (EEx "U25" (EPred "r" [(EVar "U25")]))) (EAnd (ENeg (EPred "s" [(EVar "X443_56")])) (EEx "V27" (EPred "s" [(EVar "V27")])))) ]] ) ).
apply (mkBinaryNode ( BetaOr [[ EOr (EAnd (ENeg (EPred "r" [(EVar "X749_59")])) (EEx "A33" (EPred "r" [(EVar "A33")]))) (EAnd (ENeg (EPred "s" [(EVar "X851_60")])) (EEx "B35" (EPred "s" [(EVar "B35")]))) ]] ) ).
{
apply (mkUnaryNode ( AlphaAnd [[ EAnd (ENeg (EPred "r" [(EVar "X749_59")])) (EEx "A33" (EPred "r" [(EVar "A33")])) ]] ) ).
apply (mkUnaryNode ( DeltaEx [[ EEx "A33" (EPred "r" [(EVar "A33")]) ]] [[ (EFun "skolem@A33@0" []) ]] ) ).
exact (mkClosure [[ EPred "r" [(EFun "skolem@A33@0" [])] ]] [[ ENeg (EPred "r" [(EVar "X749_59")]) ]]).
}
{
apply (mkUnaryNode ( AlphaAnd [[ EAnd (ENeg (EPred "s" [(EVar "X851_60")])) (EEx "B35" (EPred "s" [(EVar "B35")])) ]] ) ).
apply (mkUnaryNode ( DeltaEx [[ EEx "B35" (EPred "s" [(EVar "B35")]) ]] [[ (EFun "skolem@B35@0" []) ]] ) ).
exact (mkClosure [[ ENeg (EPred "s" [(EVar "X851_60")]) ]] [[ EPred "s" [(EFun "skolem@B35@0" [])] ]]).
}
Defined.

Theorem hasTableau_T_Proof :
	hasTableau InnerSkolemization [  Neg (translate_EForm T) ] subst.
Proof.
tableaux T_Proof.
Qed.

