(** * Skolemization: a generic class for Skolemization *)

From Tableaux Require Import Prelude.All.
From Tableaux Require Import Syntax.
From Tableaux Require Import Semantics.

(** In this file, we specify Skolemization so that it can be used in a generic setting
    in tableaux proofs. We give the data it must furnish, and the properties it must
    follow. The goal is to be able to be Skolemization-independent in the definition of
    tableaux and make it work seamlessly for different instances of this class. *)
Section SkolemizationDef.
  Context {pred func var : Atom}.

  Let set_var := set_atom var.
  Let set_func := set_atom func.

  Let Term := Term_ func var.
  Let Form := Form_ pred func var.
  Let Con := list Form.

  (** We start by defining skolemization "records", which vary depending on the skolemization.
      For instance, starting from pre-inner Skolemization, we want to check that each function
      symbol generated by skolemizing the same formula is the same, so we need a kind of
      key-value map.

      For e.g., outer and inner Skolemization, we don't need a record, so it will simply be
      instantiated to [unit]. *)
  Section SkoRecord.
    Record SkoRecordData :=
      { record :> Type
      ; record_eqb :: EqBool record

      ; value_record : func -> record -> option (Form_ pred func var)
      ; join : record -> record -> record
      ; single_record : func -> Form -> record
      ; empty_record : record }.
    #[global] Arguments value_record {_} _ _.
    #[global] Arguments join {_} _ _.
    #[global] Arguments empty_record {_}.

    Section SkoRecordDataDefs.
      Context {RecordData : SkoRecordData}.

      Definition in_record (f : func) (r : RecordData) : Prop :=
        match value_record f r with
        | None => False
        | Some _ => True
        end.

      Definition mem_record (f : func) (r : RecordData) : bool :=
        match value_record f r with
        | None => false
        | Some _ => true
        end.

      Lemma mem_record_spec :
        forall (f : func) (r : RecordData),
          mem_record f r = true <-> in_record f r.
      Proof using Type.
        intros. rewrite /mem_record /in_record.
        destruct (value_record f r).
        - tauto.
        - easy.
      Qed.
    End SkoRecordDataDefs.

    Class SkoRecordSpecs (RecordData : SkoRecordData) :=
      { record_ext :
        forall (r1 r2 : RecordData),
          r1 = r2 <->
            (forall (f : func), in_record f r1 <-> in_record f r2)
      ; single_spec :
        forall (f g : func) (F : Form),
          in_record g (single_record RecordData f F) -> g = f
      ; join_spec :
        forall (f : func) (r1 r2 : RecordData),
          in_record f (join r1 r2) <-> in_record f r1 \/ in_record f r2
      ; value_record_spec1 :
        forall (f : func), @value_record RecordData f empty_record = None
      }.

    Record SkoRecord_ :=
      { data :> SkoRecordData
      ; specs :: SkoRecordSpecs data }.
  End SkoRecord.

  (** We define the first part of the Skolemization process: the data. It takes:
      - a Skolemization record,
      - a boolean predicate [is_sko], to check if a given term is a valid skolemization
        in a given context,
      - a [symbol] function, that should always return a [func] if the term [t] is a
        skolemization,
      - and an [args] function, that should always return the arguments of the term [t] if
        it is a Skolemization. *)
  Record SkolemizationData :=
    { sko_record : SkoRecord_
    ; is_sko :> Term -> Form -> sko_record -> Con -> bool
    ; symbol :
        forall {t : Term} {F : Form} {symbs : sko_record} {Gamma : Con},
          is_sko t F symbs Gamma = true -> func
    ; args :
      forall {t : Term} {F : Form} {symbs : sko_record} {Gamma : Con},
        is_sko t F symbs Gamma = true -> list (Term_ func var) }.

  Class isSkolemization (data : SkolemizationData) :=
    { is_func :
      forall {t : Term} {F : Form} {symbs : sko_record data} {Gamma : Con}
        (hsko : is_sko data t F symbs Gamma = true),
        t = Fun (symbol data hsko) (args data hsko)
    ; symbol_sound :
      forall {t : Term} {F : Form} {symbs : sko_record data} {Gamma : Con}
        (hsko : is_sko data t F symbs Gamma = true),
        get_symbol t = Some (symbol data hsko)
    ; sko_con_fv :
      forall {t : Term} {F : Form} {symbs : sko_record data} (Gamma Gamma' : Con),
        fv Gamma = fv Gamma' ->
        is_sko data t F symbs Gamma = is_sko data t F symbs Gamma'
    ; is_sko_sound :
      forall {t : Term} {F : Form} {symbs : sko_record data} {Gamma : Con}
        (hsko : is_sko data t (Neg (All F)) symbs Gamma = true) (M : Model pred func),
      exists (f : func -> list M -> M),
        (forall (mu : env M var), [[ M # [] # mu '|= Neg (All F) ]] ->
                            [[ ReplacementModel M f # [] # mu '|= Neg F{0 \to t} ]]) /\
          (forall (F : Form) (mu : env M var), [[ M # [] # mu '|= F ]] ->
                                         [[ ReplacementModel M f # [] # mu '|= F ]]) }.

  Record Skolemization_ :=
    { skoData :> SkolemizationData
    ; is_skolemization :: isSkolemization skoData }.
End SkolemizationDef.

Coercion specs : SkoRecord_ >-> SkoRecordSpecs.
Coercion is_skolemization : Skolemization_ >-> isSkolemization.

Arguments SkoRecordData : clear implicits.
Arguments SkoRecord_ : clear implicits.

Arguments SkolemizationData : clear implicits.
Arguments Skolemization_ : clear implicits.
Arguments sko_record {_ _ _} _.

Section SkoSymbolLemmas.
  Context {pred func var : Atom} {record : SkoRecord_ pred func var}.

  Existing Instance eqb_atom.

  Definition add_symbol (f : func) (F : Form_ pred func var) (r : record) : record :=
    join (single_record record f F) r.

  Lemma join_unitr :
    forall (r : record),
      join r empty_record = r.
  Proof using Type.
    intro; rewrite record_ext; intros f; split.
    - rewrite join_spec; intros [h | contra]; auto.
      unfold in_record in contra. now rewrite value_record_spec1 in contra.
    - rewrite join_spec; intros h; auto.
  Qed.

  Lemma join_unitl :
    forall (r : record),
      join empty_record r = r.
  Proof using Type.
    intro; rewrite record_ext; intros f; split.
    - rewrite join_spec; intros [contra | h]; auto.
      unfold in_record in contra. now rewrite value_record_spec1 in contra.
    - rewrite join_spec; intros h; auto.
  Qed.
End SkoSymbolLemmas.

(** ** Some classic instances *)
Section SkolemizationInstances.
  Context {pred func var : Atom}.

  Let set_var := set_atom var.
  Let set_func := set_atom func.

  Let Term := Term_ func var.
  Let Form := Form_ pred func var.
  Let Con := list Form.

  Existing Instance set_func.

  (** An instance of [SkoRecord] with [unit]. *)
  Definition SkoRecordData_unit :
    SkoRecordData pred func var.
  Proof.
    unshelve econstructor.
    - exact unit.
    - typeclasses eauto.
    - exact (fun _ _ => None).
    - exact (fun _ _ => tt).
    - exact (fun _ _ => tt).
    - exact tt.
  Defined.

  Lemma SkoRecordSpecs_unit :
    SkoRecordSpecs SkoRecordData_unit.
  Proof using Type.
    constructor.
    - intros; split; intro h; intros.
      + now cbn.
      + now destruct r1, r2.
    - now intros.
    - intros; cbn in *. tauto.
    - reflexivity.
  Qed.

  Definition sko_record_unit : SkoRecord_ pred func var.
  Proof.
    unshelve econstructor.
    - exact SkoRecordData_unit.
    - exact SkoRecordSpecs_unit.
  Defined.

  (** Generic definitions for different skolemizations *)
  (* Use this function to avoid repeating the match on useless terms *)
  Definition SkoWrapper_is_sko (t : Term_ func var) (P : func -> list (Term_ func var) -> bool) : bool :=
    match t with
    | Bound _ | Free _ => false
    | Fun f l => P f l
    end.

  (* Use this function to get the skolem symbol (it abstracts away the impossible cases) *)
  Definition SkoWrapper_symbol (t : Term_ func var) {P : func -> list (Term_ func var) -> bool}
    (hsko : SkoWrapper_is_sko t P = true) : func.
    refine
      (match t as t0 return t = t0 -> func with
       | Bound _ | Free _ => fun e => False_rect func _
       | Fun f _ => fun _ => f
       end eq_refl).
    all: now rewrite e in hsko.
  Defined.

  Definition SkoWrapper_args (t : Term_ func var) {P : func -> list (Term_ func var) -> bool}
    (hsko : SkoWrapper_is_sko t P = true) : list (Term_ func var).
  Proof.
    refine
      (match t as t0 return t = t0 -> list (Term_ func var) with
       | Bound _ | Free _ => fun e => False_rect (list (Term_ func var)) _
       | Fun _ l => fun _ => l
       end eq_refl).
    all: now rewrite e in hsko.
  Defined.

  Definition is_fv_in (S : set_atom var) (t : Term_ func var) : bool :=
    match t with
    | Bound _ | Fun _ _ => false
    | Free x => mem x S
    end.

  Definition only_fv_in (S : set_atom var) (t : Term_ func var) : bool :=
    match t with
    | Bound _ | Free _ => false
    | Fun f l => forallb (is_fv_in S) l
    end.

  (** In outer skolemization, we want to check that:
      - [t] is a functorial term [f (t1, ..., tn)],
      - such that [f] does not already appear in [Gamma],
      - and [t1, ..., tn] are actually all the free variables of [Gamma].

      As the fact that it's a functorial term is already given by [SkoWrapper_is_sko],
      we focus on defining the other aspects here. *)
  Definition OuterSkolemization_is_sko_pred (Gamma : Con) (f : func) (l : list Term) : bool :=
    negb (mem f (function_symbols Gamma)) &&
      eqb (fv l) (fv Gamma) &&
      forallb is_free l.

  Lemma OuterSkolemization_is_sko_pred_sound :
    forall (Gamma : Con) (f : func) (l : list Term),
      OuterSkolemization_is_sko_pred Gamma f l = true ->
      ~(set_in f (function_symbols Gamma)) /\
        fv l = fv Gamma /\
        (forall (t : Term), List.In t l -> exists (x : var), t = Free x).
  Proof using Type.
    intros ??? [ [ hfresh%Bool.negb_true_iff e ]%andb_prop hfree ]%andb_prop;
      repeat split.
    - rewrite -mem_spec' //.
    - rewrite -eqbIsEq //.
    - rewrite forallb_forall in hfree; intros ? hin; specialize (hfree t hin).
      now apply is_free_sound in hfree.
  Qed.

  Definition OuterSkolemizationData : SkolemizationData pred func var.
  Proof.
    unshelve econstructor.
    - exact sko_record_unit. (* in outer skolemization, we don't need to check other symbols *)
    - intros t _ _ Gamma. exact (SkoWrapper_is_sko t (OuterSkolemization_is_sko_pred Gamma)).
    - intros t ??? hsko. apply (SkoWrapper_symbol t hsko).
    - intros t ??? hsko. apply (SkoWrapper_args t hsko).
  Defined.

  Lemma OuterSkolemization_args_vars :
    forall {Gamma : Con} {t : Term} {F : Form} {symbs : sko_record_unit}
      (hsko : OuterSkolemizationData t F symbs Gamma = true),
    exists (l : list var), args OuterSkolemizationData hsko =
                        map (fun v => Free v) l.
  Proof using Type.
    intros ?????. set largs := args OuterSkolemizationData hsko.
    destruct t; try inversion hsko; cbn in hsko.
    have eargs : largs = l by reflexivity. rewrite eargs.
    have h := OuterSkolemization_is_sko_pred_sound Gamma a l.
    destruct (h hsko) as (_ & _ & hargs).
    clear largs eargs H0 hsko h.
    induction l as [|t ts IHts].
    - now exists [].
    - have ht := hargs t ltac:(now left).
      destruct ht as (x & e).
      have H : forall t, List.In t ts -> exists x : var, t = Free x.
      { intros; apply hargs. now right. }
      specialize (IHts H). destruct IHts as (l0 & el0).
      exists (x :: l0); cbn. rewrite e el0 //.
  Qed.

  Lemma OuterSkolemization_isLocallyClosed :
    forall (t : Term_ func var) (F : Form_ pred func var) (symbs : sko_record OuterSkolemizationData)
      (Gamma : list (Form_ pred func var)),
      OuterSkolemizationData t F symbs Gamma = true -> isLocallyClosed t.
  Proof using Type.
    intros ???? hsko; destruct t; cbn in *; try (inversion hsko; fail).
    apply OuterSkolemization_is_sko_pred_sound in hsko; destruct hsko as (_ & _ & hfv).
    clear Gamma symbs F; induction l as [|t ts IHts]; unfold isLocallyClosed; cbn; unfold is_empty;
      auto.
    change (bv t \union bv_list ts = \{\}); apply is_empty_union; split.
    + have h : exists x, t = Free x by apply hfv; now left.
      destruct h as (x & e); rewrite e; now cbn.
    + apply IHts; intros; apply hfv; now right.
  Qed.

  Lemma OuterSkolemization_isFunc :
    forall (t : Term_ func var) (F : Form_ pred func var) (symbs : sko_record OuterSkolemizationData)
      (Gamma : list (Form_ pred func var)) (hsko : OuterSkolemizationData t F symbs Gamma = true),
      t = Fun (symbol OuterSkolemizationData hsko) (args OuterSkolemizationData hsko).
  Proof using Type.
    intros. destruct t; cbn in *; try (inversion hsko; fail).
    reflexivity.
  Qed.

  Lemma OuterSkolemization_function_symbols :
    forall {t : Term_ func var} {F : Form_ pred func var} {symbs : sko_record OuterSkolemizationData}
      {Gamma : list (Form_ pred func var)} (hsko : OuterSkolemizationData t F symbs Gamma = true),
      function_symbols (args OuterSkolemizationData hsko) = \{\}.
  Proof using Type.
    intros; destruct t; try (inversion hsko; fail); cbn in hsko |- *;
      unfold OuterSkolemization_is_sko_pred in hsko.
    have hsko' := andb_prop _ _ hsko.
    destruct hsko' as (_ & hfree); clear hsko.
    induction l as [|t ts IHts]; auto; cbn.
    cbn in hfree; apply andb_prop in hfree; destruct hfree as [hfreet hfreets].
    rewrite set_fold_left empty_unitl IHts; auto.
    destruct t; try inversion hfreet; cbn; apply empty_unitl.
  Qed.

  Lemma isSkolemization_OuterSkolemizationData :
    isSkolemization OuterSkolemizationData.
  Proof.
    constructor.
    - apply OuterSkolemization_isFunc.
    - intros; cbn. unfold SkoWrapper_symbol. destruct t; cbn; try inversion hsko;
        reflexivity.
    - intros; cbn. destruct t; auto; cbn.
      unfold OuterSkolemization_is_sko_pred. admit.
      (* TODO actually we need that the function symbols are the same also *)
    - intros ???? hsko ?.
      destruct t; try inversion hsko.
      destruct (OuterSkolemization_args_vars hsko) as (l0 & el0).
      cbn in el0. rewrite el0.
      exists (replace_interp_func M F (symbol OuterSkolemizationData hsko) l0); split.
      + intros mu hdelta; apply satisfies_opening_with_sko; auto.
        destruct (OuterSkolemization_is_sko_pred_sound _ _ _ H0) as (hnin & _ & _).
        (* OK if [Neg (All F)] is in [Gamma], which is the case. *)
        admit.
      + intros G mu hG. unfold interpret; rewrite no_skolem_same_interp_form; auto.
        (* OK if [G] is in [Gamma], which is the case (TODO) *)
  Admitted.

  Definition OuterSkolemization : Skolemization_ pred func var.
  Proof.
    unshelve econstructor.
    - exact OuterSkolemizationData.
    - exact isSkolemization_OuterSkolemizationData.
  Defined.

  (* Definition InnerSkolemizationData : SkolemizationData pred func var. *)
  (* Proof. *)
  (*   unshelve econstructor. *)
  (*   - exact sko_record_sets. (* in inner skolemization, we also only care about freshness of the *)
  (*                               symbols *) *)
  (*   - intros t F _ symbs. *)
  (*     (* We want to check (i) that the list [l] is composed of all the free variables appearing *)
  (*        in the Skolemized formula [F], and (ii) that the symbol [f] is fresh in the set of *)
  (*        Skolem symbols already appearing in the branch. *) *)
  (*     exact (SkoWrapper_is_sko t (fun f l => andb (only_fv_in (fv F) t) (isFresh f symbs))). *)
  (*   - intros t ??? hsko. apply (SkoWrapper_symbol t hsko). *)
  (*   - intros t ??? hsko. apply (SkoWrapper_args t hsko). *)
  (* Defined. *)

  (* Lemma isSkolemization_InnerSkolemizationData : *)
  (*   isSkolemization InnerSkolemizationData. *)
  (* Proof. Admitted. *)

  (* Definition InnerSkolemization : Skolemization_ pred func var. *)
  (* Proof. *)
  (*   unshelve econstructor. *)
  (*   - exact InnerSkolemizationData. *)
  (*   - exact isSkolemization_InnerSkolemizationData. *)
  (* Defined. *)
End SkolemizationInstances.

Module ConcreteSkolemizationInstances.
  Export ConcreteSyntaxInstances.

  Definition Skolemization := Skolemization_ string string string.
End ConcreteSkolemizationInstances.
