if [[ $(basename $(pwd)) = "devtools" ]]; then
	echo "Error: this script should be used at the root of the repository."
	exit 1
fi

pandoc -s -o devtools/extra/index.html README.md

header=$(cat devtools/extra/header.html)
footer=$(cat devtools/extra/footer.html)

# Remove header/footer generated by pandoc
index=$(cat devtools/extra/index.html | awk '/<\/head>/ {seen = 1} seen {print}')
index=$(echo $index | tail -n +1 | head -n +2)

declare -A theories
theories["theories"]="Tableaux\\."
theories["examples"]=""

# Replace '/' by '.' in the hrefs
for key in ${!theories[@]}; do
	for link in $(echo "$index" | grep -o "${key}/[^\\.]*\.v"); do
		new_link=$(echo $link | sed -e "s#${key}/#${theories[${key}]}#g" \
					   | sed -e 's/\.v/\.html/g')
		index=$(echo "$index" | sed -e "s#${link}#${new_link}#g")
	done
done

echo "$header$index$footer" > devtools/extra/index.html
