From Tableaux Require Import All.

Import ATPCompat.

(** In this file, we give an example of a tableau proof of the drinker principle:
      [exists x, P x -> forall y, P y],
    both in outer and inner Skolemization.

    We start by defining the drinker formula using the extended syntax: *)
Definition drinker : EForm :=
    EEx "x" (EImp (EPred "P" [EVar "x"]) (EAll "y" (EPred "P" [EVar "y"]))).

(** In the outer Skolemization proof, we have to instantiate the drinker formula twice by
    [X] then [X2] as the first Skolemization step yields [f X]. We can then instantiate
    [X2] by [f X] to bring the proof to closure.

    In TableauxRocq, we can give this substitution as a finite list and automatically
    translate it to the system's internal substitution type using [translate_substitution]. *)
Definition outer_subst := translate_substitution [("X2", EFun "f" [ EVar "X" ])].

(** Then, there is a tableau proof of the negation (as the tableau method proceeds by
    contradiction) of the drinker formula. *)
Theorem outer_drinker_proof :
  hasTableau OuterSkolemization {{ translate_EForm (ENeg drinker) }} outer_subst.
Proof.
  (** We need to start by giving two things:
      1. the whole set of free variables in the tree
      2. the whole set of skolem symbols in the tree.

      In TableauxRocq, there is a notation [\{ x, y, .., z \}] for finite sets,
      and we use it here. *)
  exists \{ "X", "X2" \}, \{ "f" \}.

  (** Now, we can start the proof. We first apply the rule for [ENot EEx] on the [drinker]
      formula, at address [0] in the context.

      Note the [unshelve] before applying the rule: it allows us to specify the
      free-variable generated by the rule. *)
  unshelve eapply hasTableauNegEx with (i := 0).

  (** Actually, [unshelve] generates too many goals. For instance, we don't need to specify
      the first three goals, as they can easily be inferred by Rocq when we close the other
      goals. Hence, we [shelve] these goals, i.e., we tell Rocq that we delay the instantiation
      of the variables and make them disappear from the current goals. *)
  1-3: shelve.

  (** Now, the first goal is to specify the free-variable generated. *)
  1: exact "X".

  (** Then, if you have selected the right formula, the first "real" goal should always
      be closed by [reflexivity]. *)
  1: { reflexivity. }

  (** Also, whenever a goal involves computations, it suffices to invoke [esimpl] (which
      is currently simply a shortcut for [native_compute]) to simplify it. If everything
      is all right, the goal can be directly closed after.
      Here, the goal is [isFresh "X" \{ "X2" \}], which is the case.
      Hence, [now esimpl] suffices to close the goal. *)
  1: { now esimpl. }

  (** Next, we have to give the remaining free variables of the branch. This is mostly a
      redundant goal, as basically it's simply the set that we already gave, minus the
      free variable specified above. Hence, we can simply close this goal by [reflexivity]. *)
  1: { reflexivity. }

  (** This is another goal that we simply need to compute. *)
  1: { now esimpl. }

  (** We continue the proof by applying the rule for [ENot EImp] on the new formula generated
      by TableauxRocq. *)
  eapply hasTableauNegImp with (i := 0).

  (** As before, and as always after, the first goal should be closed by [reflexivity]. *)
  1: { reflexivity. }

  (** We don't need to show anything else for the rule [ENot EImp], so we can continue the proof.
      As the rule has generated 2 formulas with one at index [0] being a litteral, we can only
      apply more rules on the element at index [1] in the context.

      On a Skolemization step, we want to specify the Skolemized term, so we use the
      [unshelve] prefix to the tactic [eapply], and the 3rd goal will let us define
      our term.

      Note that we specify the skolemization used in order to make the rule appliable without
      further elaboration. *)
  unshelve eapply hasTableauNegAll with (sko := OuterSkolemization) (i := 1).

  (** As we are only interested in the 3rd goal to continue, we can always shelve (i.e., let Rocq
      infer the terms with what we give for the other goals) the first two goals after a
      Skolemization rule. *)
  1, 2: shelve.

  (** As the first two goals are shelved, the 3rd one becomes the 1st. *)
  1: exact (EFun "f" [ EVar "X" ]).

  (** Note that we close the second and third goal first, in order to resolve the metavariables
      in the first goal. The second goal is the selected formula, which should be closed by
      [reflexivity] as usual, and the third one computes the Skolem symbol from the term we
      gave, and states that it should be ["f"]. We can always close such a case by
      [reflexivity]. *)
  2, 3: reflexivity.

  (** [OuterSkolemization] stuff is basically saying that ["f"] should be fresh
      and that ["X"] are all the free variables of the branch. We can let [set_decide] do
      the job here as everything is encoded using sets. *)
  1: { now esimpl. }

  (** Now, we apply back the drinker formula, which is quite a long way off in the context. *)
  unshelve eapply hasTableauNegEx with (i := 6).

  (** We do the same first two steps as before, but with [X2] instead of [X]. *)
  1-3: shelve.
  1: exact "X2".
  1: { reflexivity. }
  1: { now esimpl. }
  1: { reflexivity. }
  1: { now esimpl. }

  (** Then, we can also reapply the [ENot EImp] rule on the formula generated by the previous
      rule application. *)
  eapply hasTableauNegImp with (i := 0).
  1: { reflexivity. }

  (** And now, we can finally find a contradiction between the litteral generated now and
      the litteral generated by the previous application of [hasTableauNegImp]. *)
  eapply hasTableauContr with (i := 0) (j := 5).

  (** Here, as we select two formulas, we should apply [reflexivity] twice. *)
  1: { reflexivity. }
  1: { reflexivity. }

  (** If everything is as expected, the goal can be closed by [reflexivity]. *)
  reflexivity.
Qed.

(** In inner Skolemization, we only have to Skolemize once as ["X"] does not appear in the
    body of the Skolemized formula. As before, we provide the substitution using a finite list,
    and call the [translate_substitution] function. *)
Definition inner_subst := translate_substitution [("X", EFun "c" [])].

(** Let's do the proof. *)
Theorem inner_drinker_proof :
  hasTableau InnerSkolemization {{ translate_EForm (ENeg drinker) }} inner_subst.
Proof.
  (** As before, we need to give both (i) the set of free variables of the tableau,
      and (ii) the set of Skolem symbols. *)
  exists \{ "X" \}, \{ "c" \}.

  (** Then, the proof proceeds as before for the first two steps. *)
  unshelve eapply hasTableauNegEx with (i := 0).
  1-3: shelve.
  1: exact "X".
  1: reflexivity.
  1: now esimpl.
  1: reflexivity.
  1: now esimpl.
  eapply hasTableauNegImp with (i := 0).
  1: reflexivity.

  (** And we give ["c"] as the Skolem symbol here. *)
  unshelve eapply hasTableauNegAll with (sko := InnerSkolemization) (i := 1).
  1, 2: shelve.
  1: exact (EFun "c" [ ]).
  2, 3: reflexivity.
  1: { now esimpl. }

  (** But now, we can directly find a contradiction between [Neg (P c)] and [P X]. *)
  eapply hasTableauContr with (i := 1) (j := 0).
  1: reflexivity.
  1: reflexivity.
  Transparent eqb. simpl.
  unfold etranslation_eform, inner_subst, translate_substitution.
  reflexivity.
Qed.
