name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      [opened, synchronize, reopened, ready_for_review]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell --run "sh configure.sh; make -f RocqMakefile"

  Bench:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell --run "sh configure.sh; make -f RocqMakefile; cd devtools; sh run-tests.sh $REPO_TOKEN"
        env:
          REPO_TOKEN: ${{ secrets.CLONE_REPO_TOKEN }}
